export { default as NavBar } from './NavBar'
export { default as HomePage } from './HomePage'
export { default as Exchanges } from './Exchanges'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as CryptoDetalis } from './CryptoDetalis'
export { default as News } from './News'
export { default as Loader } from './Loader'